
version: '1'

services:
  microservice-registry:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RABBIT_ADDRESS=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
