
version: '3'

services:
  kpj_homework:
    image: "kpj_homework"
    ports:
      - "${SERVICE_EXPOSED_PORT}:8080"
    environment:
      SPRING_RABBITMQ_ADDRESSES: "${RABBIT_ADDRESS:-amqp://guest:guest@host.docker.internal:5672/}"
      SERVICE_NAME: "vojtechleskovsky"
      SERVICE_EXPOSED_PORT: "41632"
      RABBITMQ_FANOUT_NAME: "kpj"
      RABBITMQ_QUEUE_NAME: "kpj.vojtechleskovsky"
