
version: '3'

services:
  kpj_homework:
    image: "kpj_homework"
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_ADDRESSES: "amqp://guest:guest@host.docker.internal:5672/"
      SERVICE_NAME: "vojtechleskovsky"
      SERVICE_EXPOSED_PORT: "5672"
      RABBITMQ_FANOUT_NAME: "kpj"
      RABBITMQ_QUEUE_NAME: "kpj.vojtechleskovsky"
