
#version: '3'

#services:
#  kpj_homework:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - RABBIT_ADDRESS=amqp://rabbit@a0a0f641839e:5672
#    depends_on:
#      - rabbitmq
#
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=guest'
#      - 'RABBITMQ_DEFAULT_USER=guest'
#    ports:
#      - '5672'
